DECLARE @valor1 INT, @valor2 INT,@valor3 INT,@valor4 INT
SET @valor1 = 10
SET @valor2 = 5
SET @valor3 = 34
SET @valor4 = 7

DECLARE @SOMA INT

SET @SOMA = @valor1 + @valor2

SELECT @SOMA AS 'SOMA DOS VALORES 1 E 2'

DECLARE @SUBTRAÇÃO INT

SET @SUBTRAÇÃO = @valor3 - @valor4

SELECT @SUBTRAÇÃO AS 'SUBTRAÇÃO DOS VALORES 3 E 4'

DECLARE @MULTIPLICAÇÃO INT
SET @MULTIPLICAÇÃO = @valor1 * @valor4
SELECT @MULTIPLICAÇÃO AS 'MULTIPLICAÇÃO DOS VALORES 1 E 4'

DECLARE @DIVISÃO FLOAT 
SET @DIVISÃO = CAST(@valor3 AS FLOAT) / @valor4 

SELECT @DIVISÃO AS 'DIVISÃO DO VALOR 3 PELO VALOR 4'

SELECT ROUND(@DIVISÃO, 2) AS 'DIVISÃO DO VALOR 3 PELO VALOR 4 COM 2 casas decimais.'