DECLARE @NOME_USUARIO VARCHAR(50)
SET @NOME_USUARIO = 'André'

DECLARE @DATA_NASCIMENTO DATETIME
SET @DATA_NASCIMENTO = '10/02/1998'

DECLARE @NUM_PETS INT
SET @NUM_PETS = 2


PRINT 'Meu nome é '+ @NOME_USUARIO + ', nasci em '+	FORMAT(@DATA_NASCIMENTO, 'dd/MM/yyyy') + ' e tenho '+ CAST(@NUM_PETS AS VARCHAR (20))+ ' pets'

